apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-ruciod-int-deckardtest3
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rucio-daemons
      release: cms-ruciod-int
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rucio-daemons
        release: cms-ruciod-int
        rucio-daemon: deckardtest3
        rucioInstance: int
    spec:
      containers:
      - args:
        - infinity
        command:
        - /deckard/deckard_run.sh
        env:
        - name: RUCIO_CFG_ACCOUNTS_SPECIAL_ACCOUNTS
          valueFrom:
            secretKeyRef:
              key: accounts_special_accounts
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_CMS_GITLAB
          valueFrom:
            secretKeyRef:
              key: cms_gitlab
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_CMS_MONIT
          valueFrom:
            secretKeyRef:
              key: cms_monit
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_COMMON_LOGLEVEL
          valueFrom:
            secretKeyRef:
              key: common_loglevel
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_CONVEYOR_BRING_ONLINE
          valueFrom:
            secretKeyRef:
              key: conveyor_bring_online
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_CONVEYOR_CACERT
          valueFrom:
            secretKeyRef:
              key: conveyor_cacert
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_CONVEYOR_FTSHOSTS
          valueFrom:
            secretKeyRef:
              key: conveyor_ftshosts
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_CONVEYOR_FTSMONHOSTS
          valueFrom:
            secretKeyRef:
              key: conveyor_ftsmonhosts
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_CONVEYOR_USERCERT
          valueFrom:
            secretKeyRef:
              key: conveyor_usercert
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_DEFAULT
          valueFrom:
            secretKeyRef:
              key: database_default
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_ECHO
          valueFrom:
            secretKeyRef:
              key: database_echo
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_MAX_OVERFLOW
          valueFrom:
            secretKeyRef:
              key: database_max_overflow
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_POOL_RECYCLE
          valueFrom:
            secretKeyRef:
              key: database_pool_recycle
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_POOL_RESET_ON_RETURN
          valueFrom:
            secretKeyRef:
              key: database_pool_reset_on_return
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_POOL_SIZE
          valueFrom:
            secretKeyRef:
              key: database_pool_size
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_POOL_TIMEOUT
          valueFrom:
            secretKeyRef:
              key: database_pool_timeout
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_DATABASE_SCHEMA
          valueFrom:
            secretKeyRef:
              key: database_schema
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MESSAGING_CACHE_BROKERS
          valueFrom:
            secretKeyRef:
              key: messaging_cache_brokers
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MESSAGING_CACHE_VONAME
          valueFrom:
            secretKeyRef:
              key: messaging_cache_voname
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MESSAGING_FTS3_BROKERS
          valueFrom:
            secretKeyRef:
              key: messaging_fts3_brokers
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MESSAGING_FTS3_VONAME
          valueFrom:
            secretKeyRef:
              key: messaging_fts3_voname
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MESSAGING_HERMES_BROKERS
          valueFrom:
            secretKeyRef:
              key: messaging_hermes_brokers
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MESSAGING_HERMES_DESTINATION
          valueFrom:
            secretKeyRef:
              key: messaging_hermes_destination
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MESSAGING_HERMES_EMAIL_FROM
          valueFrom:
            secretKeyRef:
              key: messaging_hermes_email_from
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MESSAGING_HERMES_PORT
          valueFrom:
            secretKeyRef:
              key: messaging_hermes_port
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MESSAGING_HERMES_SSL_CERT_FILE
          valueFrom:
            secretKeyRef:
              key: messaging_hermes_ssl_cert_file
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MESSAGING_HERMES_SSL_KEY_FILE
          valueFrom:
            secretKeyRef:
              key: messaging_hermes_ssl_key_file
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MESSAGING_HERMES_VONAME
          valueFrom:
            secretKeyRef:
              key: messaging_hermes_voname
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MONITOR_CARBON_SERVER
          valueFrom:
            secretKeyRef:
              key: monitor_carbon_server
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MONITOR_ENABLE_METRICS
          valueFrom:
            secretKeyRef:
              key: monitor_enable_metrics
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MONITOR_METRICS_PORT
          valueFrom:
            secretKeyRef:
              key: monitor_metrics_port
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_MONITOR_USER_SCOPE
          valueFrom:
            secretKeyRef:
              key: monitor_user_scope
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_POLICY_LFN2PFN_ALGORITHM_DEFAULT
          valueFrom:
            secretKeyRef:
              key: policy_lfn2pfn_algorithm_default
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_POLICY_LFN2PFN_MODULE
          valueFrom:
            secretKeyRef:
              key: policy_lfn2pfn_module
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_POLICY_PERMISSION
          valueFrom:
            secretKeyRef:
              key: policy_permission
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_POLICY_SCHEMA
          valueFrom:
            secretKeyRef:
              key: policy_schema
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_POLICY_SUPPORT
          valueFrom:
            secretKeyRef:
              key: policy_support
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_TRACE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: trace_password
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_TRACER_KRONOS_BROKERS
          valueFrom:
            secretKeyRef:
              key: tracer_kronos_brokers
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_TRACER_KRONOS_CHUNKSIZE
          valueFrom:
            secretKeyRef:
              key: tracer_kronos_chunksize
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_TRACER_KRONOS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: tracer_kronos_password
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_TRACER_KRONOS_PORT
          valueFrom:
            secretKeyRef:
              key: tracer_kronos_port
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_TRACER_KRONOS_PREFETCH_SIZE
          valueFrom:
            secretKeyRef:
              key: tracer_kronos_prefetch_size
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_TRACER_KRONOS_QUEUE
          valueFrom:
            secretKeyRef:
              key: tracer_kronos_queue
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_TRACER_KRONOS_USERNAME
          valueFrom:
            secretKeyRef:
              key: tracer_kronos_username
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_CFG_TRACER_KRONOS_VONAME
          valueFrom:
            secretKeyRef:
              key: tracer_kronos_voname
              name: cms-ruciod-int-rucio-daemons.cfg
        - name: RUCIO_DAEMON
          value: deckardtest3
        - name: RUCIO_DAEMON_ARGS
          value: ' --total-workers 1 --include-rses="cms_type=test"  --chunk-size
            10'
        - name: GLOBUS_THREAD_MODEL
          value: pthread
        - name: RUCIO_HOME
          value: /opt/rucio/deckard
        - name: X509_USER_PROXY
          value: /opt/proxy/x509up
        image: piperov/deckard:latest
        imagePullPolicy: Always
        name: rucio-daemons
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 700m
            memory: 200Mi
          requests:
            cpu: 700m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/proxy
          name: proxy-volume
        - mountPath: /etc/grid-security/certificates
          name: ca-volume
        - mountPath: /var/cache/consistency-dump
          name: consistency-dump
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: proxy-volume
        secret:
          defaultMode: 420
          secretName: cms-ruciod-int-rucio-x509up
      - name: ca-volume
        secret:
          defaultMode: 420
          secretName: cms-ruciod-int-rucio-ca-bundle-reaper
      - name: consistency-dump
        persistentVolumeClaim:
          claimName: cms-consistency-int-report-pvc
